[workspace]
members = [
    "crates/neuroxide",
    "crates/mempool",
    "bin"
]
resolver = "3"


[workspace.dependencies]
approx = "0.5.1"
libc = "0.2.174"
num = "0.4.3"
ndarray = { version = "0.16.1", features = ["matrixmultiply-threading", "blas"] }
blas-src = { version = "0.11", features = ["intel-mkl"] }
once_cell = "1.21.3"
petgraph = "0.8.2"
rand = "0.9.2"
pkg-config = "0.3.32"
trait-set = "0.3.0"
cc = "1.2.3"

